%YAML:1.0
#起始与终止
start_index: 1
end_index: 700

#点云分辨率
voxel_grid: 0.02
#是否实时可视化
visualize_pointcloud: 1
#最小匹配数量
min_good_match: 10
#最小内点
min_inliers: 5
#最大运动误差
max_norm: 0.3

detector: GridFAST
descriptor: SIFT
good_match_threshold: 4

#camera
cx: 325.5
cy: 253.5
fx: 518.0
fy: 519.0
scale: 1000.0

keyframe_threshold: 0.1
max_norm_lp: 5.0
# Loop closure
check_loop_closure: 1
nearby_loops: 5
random_loops: 5
